### ISSUE TITLE
Connection issue to kafka brokers with different port

### ISSUE THREAD

**Issue by bazimov** [openflagr/flagr#361]
We are successfully connecting to kafka cbrokers with default port 9092 `kafka-demo:9092`.
```
- name: FLAGR_RECORDER_KAFKA_BROKERS
   value: "kafka-demo:9092"
```
But when I try AWS managed Kafka with broker port 9094, getting error. 
```
- name: FLAGR_RECORDER_KAFKA_BROKERS
   value: "b-3.name.cxxxx.c9.kafka.us-east-1.amazonaws.com:9094"
```
Is port 9092 somehow mandatory?

**Comment by zhouzhuojie** [comment]
Can you share what's the error message? I wonder if you miss any authentication or SSL config for the aws kafka connection.

**Comment by bazimov** [comment]
ENV variables set:
```
  - env:
    - name: PORT
      value: "18000"
    - name: FLAGR_RECORDER_ENABLED
      value: "true"
    - name: FLAGR_RECORDER_KAFKA_VERIFYSSL
      value: "true"
    - name: FLAGR_RECORDER_FRAME_OUTPUT_MODE
      value: "payload_raw_json"
    - name: FLAGR_RECORDER_KAFKA_VERSION
      value: "2.3.1"
    - name: FLAGR_RECORDER_KAFKA_BROKERS
      value: "b-1.nnnn.cxxxxx.c4.kafka.us-east-1.amazonaws.com:9094"
```

```
time="2020-04-23T21:10:18Z" level=fatal msg="Failed to start Sarama producer:" kafka_error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
```
